[package]
name = "rsocket_rust_test"
version = "0.0.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"

[dev-dependencies]
log = "0.4"
futures = "0.3.4"
env_logger = "0.7.1"
rsocket_rust = { version = "0.5.0", features = ["frame"] }
rsocket_rust_transport_tcp = { version = "0.5.0" }
rsocket_rust_transport_websocket = { version = "0.5.0" }
bytes = "0.5.4"
hex = "0.4.2"
rand = "0.7.3"

[dev-dependencies.tokio]
version = "0.2.11"
default-features = false
features = ["full"]
