[package]
name = "rsocket_rust_test"
version = "0.0.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"

[dev-dependencies]
log = "0.4"
futures = "0.3.3"
env_logger = "0.7.1"
rsocket_rust = { path = "../rsocket" }
rsocket_rust_transport_tcp = { path = "../rsocket-transport-tcp" }
rsocket_rust_transport_websocket = { path = "../rsocket-transport-websocket" }

[dev-dependencies.tokio]
version = "0.2.11"
default-features = false
features = ["full"]


