[package]
name = "rsocket_rust_test"
version = "0.0.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"
publish = false

[dev-dependencies]
log = "0.4"
futures = "0.3.8"
env_logger = "0.8.2"
bytes = "0.6.0"
hex = "0.4.2"
rand = "0.7.3"
serde = "1.0.118"
serde_derive = "1.0.118"

[dev-dependencies.rsocket_rust]
version = "0.6.0"
features = ["frame"]

[dev-dependencies.rsocket_rust_transport_tcp]
version = "0.6.0"

[dev-dependencies.rsocket_rust_transport_websocket]
version = "0.6.0"

[dev-dependencies.rsocket_rust_messaging]
version = "0.6.0"

[dev-dependencies.tokio]
version = "0.3.5"
default-features = false
features = ["full"]
