[package]
name = "rsocket"
version = "0.1.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
bytes = "0.4.12"
tokio = "0.1"
hex = "0.3.2"
futures = "0.1.28"
