[package]
name = "rsocket_rust_transport_websocket"
version = "0.5.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
rsocket_rust = { path = "../rsocket", features = ["frame"] }
futures = "0.3.4"
bytes = "0.5.4"
url = "2.1.1"
tokio-tungstenite = "0.10.1"

[dependencies.tokio]
version = "0.2.11"
default-features = false
features = [ "rt-core", "rt-threaded", "tcp", "sync", "stream" ]
