[package]
name = "rsocket_rust_transport_wasm"
version = "0.5.2"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/rsocket/rsocket-rust"
homepage = "https://github.com/rsocket/rsocket-rust"
description = "WASM Websocket RSocket transport implementation."

[dependencies]
bytes = "0.5.4"
wasm-bindgen-futures = "0.4.10"
futures-channel = "0.3.4"
futures-util = "0.3.4"
js-sys = "0.3.37"
serde = "1.0.106"
serde_derive = "1.0.106"

[dependencies.rsocket_rust]
path = "../rsocket"
features = ["frame"]

[dependencies.wasm-bindgen]
version = "0.2.60"
features = ["serde-serialize"]

[dependencies.web-sys]
version = "0.3.37"
features = [
  "FileReader",
  "ProgressEvent",
  "Blob",
  "ErrorEvent",
  "MessageEvent",
  "WebSocket",
  "Event",
]
