[package]
name = "rsocket_rust_transport_wasm"
version = "0.5.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
rsocket_rust = { path = "../rsocket" }

[dependencies.web-sys]
version = "0.3"
features = [
  "ErrorEvent",
  "MessageEvent",
  "WebSocket",
]