[package]
name = "rsocket_rust_messaging"
version = "0.1.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
futures = "0.3.4"
bytes = "0.5.4"
serde = "1.0.106"
serde_json = "1.0.52"
serde_cbor = "0.11.1"
hex = "0.4.2"

[dependencies.rsocket_rust]
path = "../rsocket"
features = ["frame"]