[package]
name = "rsocket_rust_transport_tcp"
version = "0.5.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"

[dependencies]
rsocket_rust = { version = "0.5.0", path = "../rsocket" }
